package MiniProject;

import javax.swing.JOptionPane;
import java.util.Random;

public class Siamese extends javax.swing.JFrame {

    public Siamese() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Siamese Created By Nasreen");

        jLabel1.setFont(new java.awt.Font("TH Chakra Petch", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("เสี่ยงเซียมซี");

        jLabel2.setFont(new java.awt.Font("TH Chakra Petch", 1, 36)); // NOI18N
        jLabel2.setText("ผลการทำนาย");

        btnExit.setFont(new java.awt.Font("TH Chakra Petch", 1, 24)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnRun.setFont(new java.awt.Font("TH Chakra Petch", 1, 24)); // NOI18N
        btnRun.setText("เขย่าเซียมซี");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MiniProject/cc.png"))); // NOI18N

        tarResult.setEditable(false);
        tarResult.setColumns(20);
        tarResult.setFont(new java.awt.Font("TH Chakra Petch", 0, 24)); // NOI18N
        tarResult.setRows(5);
        jScrollPane1.setViewportView(tarResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnRun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRun)
                    .addComponent(btnExit))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {                                       
        String[] siameses = {"ใบเซี่ยมซี่ที่ 19\n" + "  คําทํานายที่สิบเก้า เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะมีความร้อนใจด้วยการ\n"
            + "เจ็บป่วย แต่ลาภผลน้อย เนื้อคู่ช่วยท่านได้ แต่ความรักอาจจะมีอุปสรรคบ้าง การ\n"
            + "งานดี ท่านควรหมั่นไหว้พระกวนอิมโพธิสัตว์ สิ่งร้ายอาจจะกลายเป็นดี",
            "ใบเซี่ยมซี่ที่ 20\n" + "   คําทํานายที่ยี่สิบ เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ ไม่มีอุปสรรค จะทําการใดก็ดี\n"
            + "หมด การงานควรระวัง การมีปากเสียงกับผู้อื่น เจ็บป่วยไม่มี เนื้อคู่เป็นผุ้มีบุญ\n"
            + "สรรพสิ่งสมประสงค์ดีนักแล",
            "ใบเซี่ยมซี่ที่ 21\n" + "   คําทํานายที่ยี่สิบเอ็ด เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะมีโชคลาภและจะมีผู้\n"
            + "หใญ่มาคุ้มครอง การงานเจริญรุ่งเรือง เนื้อคู่อยู่ไม่ไกล เจ็บป่วยจะหายเร็ว สรรพสิ่ง\n"
            + "สมประสงค์ แต่ควรหมั่นไหว้พระทําบุญสร้างบารมีเอาไว้บ้าง เพื่อภายหน้า\n"
            + "ลูกหลานจะได้ดี เพราะที่ทําเอาไว้",
            "ใบเซี่ยมซี่ที่ 22\n" + "   ทํานายที่ยี่สิบสอง เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ เปรียบเหมือนต้นไม้ที่กําลัง\n"
            + "เขียวชะอุ่ม หมายถึงจะได้ลาภเงินทองไหลมาเทมา การงานจะเจริญก้าวหน้า เนื้อคู่\n"
            + "จะเป็นผู้ช่วยให้ท่านเจริญยิ่งขึ้น เจ็บป่วยไม่มี สรรพสิ่งสมดังปรารถนาทุกประการดี\n"
            + "นักแล",
            "ใบเซี่ยมซี่ที่ 23\n" + "   คําทํานายที่ยี่สิบสาม เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะเกิดถ้วยความให้เกรง\n"
            + "สตรีเป็นศัตรูจงหนัก มิฉะนั้น จะถูกฟ้องหาเพราะชู้เมีย ไม่ควรเดินทางกลางคืน\n"
            + "การงานไม่มีอุปสรรค อาจจะเจ็บป่วยเสียเงินทอง จึงควรไหว้พระให้ท่านคุ้มครอง\n"
            + "สิ่งต่าง ๆ อาจกลายเป็นดี",
            "ใบเซี่ยมซี่ที่ 24\n" + "   คําทํานายที่ยี่สิบสี่ เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะได้รับความร้อนใจมิฉะนั้น\n"
            + "อาจจะมีอันตราย การงานมีอุปสรรค เจ็บป่วยหายยาก มีบุตรเลี้ยงยาก จงหมั่นไป\n"
            + "ไหว้เทพเจ้าแห่งชะตาราศรี (ไท่ส่วย-เอี้ย) แล้วทุกสิ่งจะกลายเป็นดี",
            "ใบเซี่ยมซี่ที่ 25\n" + "   คําทํานายที่ยี่สิบห้า เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะได้ โชคลาภและอํานาจ\n"
            + "การค้าขายรุ่งเรือง เจ็บป่วยจะมีหมอดีมารักษา เนื้อคู่อยู่ด้วยกันจะประเสริฐ ท่าน\n"
            + "จะได้บุตรที่ดี สรรพสิ่งสมประสงค์ดีนักแล",
            "ใบเซี่ยมซี่ที่ 26\n" + "   คําทํานายที่ยี่สิบหก เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะมีผู้มาให้โชคลาภ การ\n"
            + "งานอาจจะมีอุปสรรค เจ็บป่วยหายเร็ว ไม่ช้าจะได้เนื้อคู่ ท่านควรจะหมั่นไหว้พระ\n"
            + "และเทพเจ้าแห่งโชคลาภ (ใช้ซิ้งเอี้ย) แล้วการค้าจะดี",
            "ใบเซี่ยมซี่ที่ 27\n" + "   คําทํานายที่ยี่สิบเจ็ด เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะเสียทรัพย์และของรัก\n"
            + "จงระวังในการเดินทางไกล การค้าไม่มีโชคลาภ เจ็บป่วยหายยาก ท่านควรจะไป\n"
            + "ไหว้พระและขอพรจากเทพเจ้าแห่งยา (หั่วท้อเซียงซือ) แล้วสรรพสิ่งต่าง ๆ จะ\n"
            + "กลายเป็นดี",
            "ใบเซี่ยมซี่ที่ 28\n" + "   คําทํานายที่ยี่สิบแปด เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ เปรียบเหมือนพระ\n"
            + "อาทิตย์อันร้อนแรง หมายถึงการงานจะเจริญรุ่งเรือง เจ็บป่วยจะมีหมอดีมารักษา\n"
            + "จะมีเนื้อคู่ที่พร้อมด้วยทรัพย์สมบัติ สรรพสิ่งที่ขอจะได้สมดังใจหมายแล",
            "ใบเซี่ยมซี่ที่ 29\n" + "   คําทํานายที่ยี่สิบเก้า เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้จะได้ยศฐาบรรดาศักดิ์ และ\n"
            + "สรรพสิ่งลาภจะบริบูรณ์ด้วยทรัพย์สมบัติ การงานเจริญรุ่งเรือง ไม่มีโรคภัยอันตราย\n"
            + "ความรักสมหวัง สรรพสิ่งไม่มีอุปสรรคดีนักแล",
            "ใบเซี่ยมซี่ที่ 30\n" + "   คําทํานายที่สามสิบ เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ ไม่สมดังใจหมายจะเกิด\n"
            + "ความร้อนใจ เจ็บป่วยไข้หายยาก และอาจจะเสียของรักไป ท่านควรจะหมั่นขอพร\n"
            + "จากพระกวนอิมโพธิสัตว์และเทพเจ้าแห่งยา(หั่วท้อเซียงซือ) สิ่งร้ายจะกลายเป็นดี",
            "ใบเซี่ยมซี่ที่ 31\n" + "   คําทํานายที่สามสิบเอ็ด เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะได้ลาภเพราะความ\n"
            + "ฝัน จะได้ผ้าผ่อนของใช้สอยสรรพสิ่งไม่เหน็ดเหนื่อย การงานไม่มีอุปสรรค อายุยืน\n"
            + "ยาว จะมีเนื้อคู่และบุตรสุดที่รัก ถ้าเป็นความจะชนะแล",
            "ใบเซี่ยมซี่ที่ 32\n" + "   คําทํานายที่สามสิบสอง เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จักได้ลาภแก้วแหวน\n"
            + "เงินทอง บริบูรณ์ไปด้วยสมบัติการงานก้าวหน้า อนาคตรุ่งเรือง เนื้อคู่มีบุญ อายุยืน\n"
            + "ยาว สรรพสิ่งสมดังประสงค์ดีนักแล",
            "ใบเซี่ยมซี่ที่ 33\n" + "   คําทํานายที่สามสิบสาม เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ เปรียบเหมือนพระ\n"
            + "อาทิตย์อันร้อนแรง หมายถึงการงานจะเจริญรุ่งเรือง เจ็บป่วยจะมีหมอดีมารักษา\n"
            + "จะมีเนื้อคู่ที่พร้อมด้วยทรัพย์สมบัติ สรรพสิ่งที่ขอจะได้สมดังใจหมายแล",
            "ใบเซี่ยมซี่ที่ 34\n" + "   คําทํานายที่สามสิบสี่ เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะมีการเจ็บป่วยอยู่บ้าง\n"
            + "การค้าขายไม่คล่องตัว โชคลาภยังมีน้อย เนื้อคู่จะช่วยท่านได้ จงหมั่นไหว้พระ\n"
            + "ทําบุญขอพรให้มาก ๆ จะสมปรารถนาทุกประการ",
            "ใบเซี่ยมซี่ที่ 35\n" + "   คําทํานายที่สามสิบห้า เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ จะได้ลาภและเนื้อคู่ การ\n"
            + "งานไม่มีอุปสรรค เจ็บป่วยจะมีหมอดีมารักษา มิฉะนั้นจะมีผู้ใหญ่คุ้มครอง จงหมั่น\n"
            + "ไหว้พระขอพรจะดีนักแล",
            "ใบเซี่ยมซี่ที่ 36\n" + "   คําทํานายที่สามสิบหก เซียมซีใบนี้ว่าด้วย ชะตาชีวิตช่วงนี้ เข้าสู่โชคลาภจะมี\n"
            + "ผู้สูงอายุมาให้โชค มิฉะนั้นจะมีเนื้อคู่พร้อมด้วยทรัพย์สมบัติ การค้าขายไม่มี\n"
            + "อุปสรรค เจ็บป่วยจะมีหมอดีมารักษา สรรพสิ่งดังใจหมาย ถ้าเป็นความจะชนะแล"};
        Random rand = new Random();
        int r = rand.nextInt(siameses.length);
        tarResult.setText("" + siameses[r]);
    }                                      

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int option = JOptionPane.showConfirmDialog(rootPane, "คุณแน่ใจหรือไม่?");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siamese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siamese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siamese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siamese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siamese().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tarResult;
    // End of variables declaration                   
}
